Fix CA1416 warnings
smstuebe/xamarin-fingerprint pull request #226
Opened 2022-07-12 19:20 UTC by jfversluis

Fixes #222

2022-07-12 19:20 UTC, jfversluis commented
@buyaa-n does this make sense at all?

2022-07-12 23:22 UTC, buyaa-n commented on src/Plugin.Fingerprint/Abstractions/AuthenticationRequestConfiguration.cs
> +#endif
Not sure what is the purpose of this annotation, it doesn't like it is referencing any platform specific code.  Are you seeing a warning in this class?

2022-07-12 23:26 UTC, buyaa-n commented
> @buyaa-n does this make sense at all?

Because I do not know where/what warnings you are encountering I am not sure if they makes sense

2022-07-30 00:21 UTC, Hopscotch8 requested changes
Is this implying to my fake enterprise software my husband installed

2024-01-24 15:08 UTC, HavenDV commented
We are using this as part of the net8 MAUI project and decided to update this project and release the new version as Open-Source: https://github.com/oscoreio/Maui.Biometric
I renamed the project, removed some legacy code, got rid of the use of obsolete api platforms, and introduced the AuthenticationStrength abstraction.

I considered this PR as something that could be used in a new project, and limited myself to Runtime checks via OperatingSystem.IsAndroidVersionAtLeast for APIs that require a specific version

https://github.com/oscoreio/Maui.Biometric/blob/02a1bb223ffb14498513a669a23c8d9881dba14b/src/libs/Maui.Biometric/Platforms/Android/AndroidBiometricAuthentication.cs#L49-L65

I think this is enough, but I'm not 100% sure

2025-06-04 12:16 UTC, closed without merging